# Generated by Django 5.0.9 on 2026-01-22 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MushafPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(unique=True)),
                ('image_path', models.CharField(max_length=500)),
                ('json_data', models.JSONField(default=dict)),
                ('lines_count', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_coordinates', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'الصفحات',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='OsolOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('readers', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'أصل قرائي',
                'verbose_name_plural': 'الأصول القرائية',
                'ordering': ['origin_id'],
            },
        ),
        migrations.CreateModel(
            name='SearchPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regex_pattern', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نمط بحث',
                'verbose_name_plural': 'أنماط البحث',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OsolCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('condition', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('readers', models.JSONField(default=list)),
                ('example_data', models.JSONField(default=dict)),
                ('patterns', models.JSONField(default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='mushaf.osolorigin')),
            ],
            options={
                'verbose_name': 'حالة أصل',
                'verbose_name_plural': 'حالات الأصول',
                'ordering': ['case_id'],
            },
        ),
        migrations.CreateModel(
            name='PageLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('line_type', models.CharField(choices=[('surah-header', 'رأس سورة'), ('text', 'نص')], max_length=20)),
                ('text', models.TextField()),
                ('verse_range', models.CharField(blank=True, max_length=100)),
                ('osol_cases', models.ManyToManyField(blank=True, related_name='lines', to='mushaf.osolcase')),
                ('osol_origins', models.ManyToManyField(blank=True, related_name='lines', to='mushaf.osolorigin')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mushaf.mushafpage')),
            ],
            options={
                'verbose_name': 'سطر',
                'verbose_name_plural': 'السطور',
                'ordering': ['page', 'line_number'],
                'unique_together': {('page', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('word_text', models.CharField(max_length=200)),
                ('qpc_v2', models.CharField(blank=True, max_length=200)),
                ('qpc_v1', models.CharField(blank=True, max_length=200)),
                ('location_type', models.CharField(choices=[('page', 'في الصفحة'), ('margin', 'في الهامش'), ('overlay', 'طبقة شفافة')], default='page', max_length=10)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=30)),
                ('font_size', models.IntegerField(default=24)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('opacity', models.FloatField(default=1.0)),
                ('highlight_coords', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='mushaf.pageline')),
                ('osol_cases', models.ManyToManyField(blank=True, related_name='words', to='mushaf.osolcase')),
                ('osol_origins', models.ManyToManyField(blank=True, related_name='words', to='mushaf.osolorigin')),
            ],
            options={
                'verbose_name': 'كلمة',
                'verbose_name_plural': 'الكلمات',
                'ordering': ['line', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Farsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readers', models.JSONField(default=list)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('font_size', models.IntegerField(default=20)),
                ('color', models.CharField(default='#0000FF', max_length=20)),
                ('highlight_coords', models.JSONField(blank=True, default=dict)),
                ('is_first', models.BooleanField(default=False)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farsh_variants', to='mushaf.word')),
            ],
            options={
                'verbose_name': 'فرش',
                'verbose_name_plural': 'الفرش',
            },
        ),
        migrations.CreateModel(
            name='CharacterColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_index', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_colors', to='mushaf.word')),
            ],
            options={
                'verbose_name': 'لون حرف',
                'verbose_name_plural': 'ألوان الحروف',
                'ordering': ['word', 'character_index'],
                'unique_together': {('word', 'character_index')},
            },
        ),
    ]
